### ISSUE TITLE
example stm32l0 hello build fails in dev-unicorn

### ISSUE THREAD

**Issue by dluksMq** [TrackNet/bootloader#2]
#include "boottab.h" is missing
Also the makefile is calling python. On ubuntu that will call python2.x

**Comment by mkuyper** [comment]
Thanks for your report. With the acquisition of TrackNet by Semtech, the bootloader has graduated to the LoRa Basics™ program and is now available and maintained here: https://github.com/lorabasics/basicloader

Therefore, this repository will no longer be updated.

**Comment by dluksMq** [comment]
Thanks Mike. I'll check that out.
